// Generated by Wrangler by running `wrangler types`

interface Env {
	WHATSAPP_DURABLE_OBJECT: DurableObjectNamespace<import('./src/index').WhatsappDurableObject>;
	VERIFY_TOKEN: string;
	WHATSAPP_TOKEN: string;
}
